version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: "/adapters/nfs4fs"
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns: ["*"]

  - package-ecosystem: cargo
    directory: "/adapters/nfs4fs"
    schedule:
      interval: weekly
    groups:
      python-native-dependencies:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: "/adapters/vfsi-fsspec"
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: "/adapters/vsmb"
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: "/adapters/vsmb"
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: "/adapters/vsmbfs"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
