[workspace]
members = [
    "crates/vnfs",
    "crates/vfsi-core",
    "crates/vfsi-sync",
    "crates/vfsi-nfs",
    "crates/vfsi-smb",
    "crates/vfsi-local",
    "crates/nfsv41-sys",
    "bindings/c",
    "third-party/libntirpc-sys",
]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5.17", features = ["derive"] }
libc = "0.2"
libntirpc-sys = "0.2.3"
nfsv41-sys = { path = "crates/nfsv41-sys", version = "0.1.6" }
xdr-codec = "0.4.4"
xdrgen = "0.4.4"
vfsi-core = { path = "crates/vfsi-core", version = "0.1.1" }
vfsi-local = { path = "crates/vfsi-local", version = "0.1.1" }
vfsi-nfs = { path = "crates/vfsi-nfs", version = "0.1.1" }
vfsi-smb = { path = "crates/vfsi-smb", version = "0.1.1" }
vfsi-sync = { path = "crates/vfsi-sync", version = "0.1.2" }

[patch.crates-io]
libntirpc-sys = { path = "third-party/libntirpc-sys" }
