[workspace]
members = [
    "crates/vnfs",
    "crates/vfsi-core",
    "crates/vfsi-sync",
    "crates/vfsi-nfs",
    "crates/vfsi-smb",
    "crates/vfsi-local",
    "crates/vfsi-uring",
    "crates/nfsv41-sys",
    "bindings/c",
]
resolver = "2"

[workspace.dependencies]
bitfields = "3.1.0"
clap = { version = "4.5.17", features = ["derive"] }
libc = "0.2"
libntirpc-sys = "0.3.0"
nfsv41-sys = { path = "crates/nfsv41-sys", version = "0.1.10" }
xdr-codec = "0.4.4"
xdrgen = "0.4.4"
vfsi-core = { path = "crates/vfsi-core", version = "0.1.8" }
vfsi-local = { path = "crates/vfsi-local", version = "0.1.7" }
vfsi-uring = { path = "crates/vfsi-uring", version = "0.1.0" }
vfsi-nfs = { path = "crates/vfsi-nfs", version = "0.1.8" }
vfsi-smb = { path = "crates/vfsi-smb", version = "0.1.6" }
vfsi-sync = { path = "crates/vfsi-sync", version = "0.1.9" }
