[package]
name = "vnfs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Vectorized NFS client API in Rust"
readme = "README.md"
repository = "https://github.com/vmingchen/vnfs"
keywords = ["NFS", "vectorized"]

[dependencies]
