[workspace]
members = ["vnfs", "examples/sum", "examples/sum_proto", "examples/sum_server"]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5.17", features = ["derive"] }
libntirpc-sys = "0.1.0"
xdr-codec = "0.4.4"
xdrgen = "0.4.4"
