NFS_Core_Param {
  Protocols = 4;
}

NFSV4 {
  Minor_Versions = 1, 2;
  Graceless = true;
  Only_Numeric_Owners = true;
}

EXPORT {
  Export_Id = 77;
  Path = /export;
  Pseudo = /;
  Access_Type = RW;
  Squash = None;
  SecType = sys;
  Protocols = 4;
  Transports = TCP;

  FSAL {
    Name = VFS;
  }
}
