[package]
name = "vnfs"
version = "0.0.2"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Vectorized NFS client API in Rust"
readme = "README.md"
repository = "https://github.com/vmingchen/vnfs"
keywords = ["NFS", "vectorized"]

[dependencies]
libc = { workspace = true }
libntirpc-sys = { workspace = true }
nfsv41-sys = { workspace = true }
