schema_version = 1

[[component]]
id = "git"
kind = "application-port"
maturity = "experimental"
repository = "https://github.com/vfsi/git"
planned_repository = "https://github.com/vfsi/port-git"
upstream = "https://github.com/git/git"
upstream_base = "1a3e64c6c4a623626ff0687008732a8e007e2a1c"
integration_branch = "vfsi"
revision = "d80fcde366b80dadc214bff91bbdb10bbc7ae99d"
vfsi_c_abi = 3
backends = ["dummy", "nfs"]
compatibility_test = "ci/ports/check-git.sh"

[[component]]
id = "rsync"
kind = "application-port"
maturity = "experimental"
repository = "https://github.com/vfsi/rsync"
planned_repository = "https://github.com/vfsi/port-rsync"
upstream = "https://github.com/RsyncProject/rsync"
upstream_base = "7fef1c827ef19bce7d3d21009b8537768e627101"
integration_branch = "vfsi"
revision = "e3ddd9911ec33a6d9468741f27549f863d269aa3"
vfsi_c_abi = 3
backends = ["dummy", "nfs"]
compatibility_test = "ci/ports/check-rsync.sh"

[[component]]
id = "nfs-ganesha"
kind = "test-infrastructure"
maturity = "validated"
repository = "https://github.com/vfsi/nfs-ganesha"
planned_repository = "https://github.com/vfsi/infra-nfs-ganesha"
upstream = "https://github.com/ffilz/nfs-ganesha"
upstream_base = "06528886251bbaf94f6d0aaff95cea90ef0cd748"
integration_branch = "xattr"
planned_integration_branch = "vfsi-ci"
revision = "ec1993746f815f32396f0de36cc7614658a33173"
vfsi_c_abi = 0
backends = ["nfs"]
compatibility_test = "ci/nfs-ganesha/Dockerfile"
