[package]
name = "vfsi-smb"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Vectorized SMB2 and SMB3 filesystem client"
repository = "https://github.com/vmingchen/vnfs"

[features]
default = []
server-copy = []

[dependencies]
futures-util = "0.3"
libc = { workspace = true }
smb2 = "0.21.0"
tokio = { version = "1", features = ["rt-multi-thread"] }
vfsi-core = { workspace = true }
vfsi-sync = { workspace = true }
