NFS_CORE_PARAM {
    Enable_NLM = false;
    Enable_RQUOTA = false;
    Protocols = 4;
    NFS_Port = 2049;
}

NFSV4 {
    Graceless = true;
    RecoveryBackend = fs_ng;
    Minor_Versions = 1;
    UseGetpwnam = true;
}

NFS_KRB5 {
    PrincipalName = "nfs@localhost.";
    KeytabPath = "/tmp/vnfs-gss/server.keytab";
    Active_krb5 = true;
}

EXPORT {
    Export_Id = 91;
    Path = "/export/vnfs-gss-test";
    Pseudo = /;
    Access_Type = RW;
    SecType = krb5, krb5i;
    Squash = All_Squash;
    Anonymous_Uid = 1000;
    Anonymous_Gid = 1000;
    Protocols = 4;
    Transports = TCP;
    FSAL {
        Name = VFS;
    }
}
