[kdcdefaults]
    kdc_ports = 61088
    kdc_tcp_ports = 61088

[realms]
    VFSI.TEST = {
        database_name = /tmp/vnfs-gss/principal
        key_stash_file = /tmp/vnfs-gss/.k5.VFSI.TEST
        acl_file = /tmp/vnfs-gss/kadm5.acl
        max_life = 1h
        max_renewable_life = 2h
        default_principal_flags = +preauth
    }
