[libdefaults]
    default_realm = VFSI.TEST
    dns_lookup_kdc = false
    dns_lookup_realm = false
    dns_canonicalize_hostname = false
    rdns = false
    udp_preference_limit = 1
    default_ccache_name = FILE:/tmp/vnfs-gss/client.ccache

[realms]
    VFSI.TEST = {
        kdc = 127.0.0.1:61088
    }

[domain_realm]
    .localhost = VFSI.TEST
    localhost = VFSI.TEST
