"""Type stubs for the Rust extension ``nfs4fs._native``."""

from typing import Dict, List, Optional, Tuple

__version__: str
CAP_SERVER_COPY: int

class NfsClient:
    def __init__(
        self,
        host: str,
        backend: str = "nfs",
        root: Optional[str] = None,
        compound_size_limit: Optional[int] = None,
        minor_version: Optional[int] = None,
        share: Optional[str] = None,
        username: str = "",
        password: str = "",
        domain: str = "",
    ) -> None: ...
    def minor_version(self) -> Optional[int]: ...
    def smb_dialect(self) -> Optional[int]: ...
    def capabilities(self) -> int: ...
    def server_copy_enabled(self) -> bool: ...
    def stat(self, path: str) -> dict: ...
    def lstat(self, path: str) -> dict: ...
    def exists(self, path: str) -> bool: ...
    def open(self, path: str, mode: str) -> int: ...
    def close(self, fd: int) -> None: ...
    def read(self, fd: int, length: int) -> bytes: ...
    def write(self, fd: int, data: bytes) -> int: ...
    def pread(self, fd: int, length: int, offset: int) -> bytes: ...
    def pwrite(self, fd: int, data: bytes, offset: int) -> int: ...
    def fseek(self, fd: int, offset: int, whence: int) -> int: ...
    def fstat(self, fd: int) -> dict: ...
    def truncate(self, path: str, size: int) -> None: ...
    def chmod(self, path: str, mode: int) -> None: ...
    def mkdir(self, path: str, mode: int) -> None: ...
    def ensure_dir(self, path: str, mode: int) -> None: ...
    def symlink(self, target: str, path: str) -> None: ...
    def readlink(self, path: str) -> str: ...
    def hardlink(self, src: str, dst: str) -> None: ...
    def getcwd(self) -> str: ...
    def chdir(self, path: str) -> None: ...
    def stat_many(
        self, paths: List[str]
    ) -> Tuple[List[Optional[dict]], Dict[int, int]]: ...
    def lstat_many(
        self, paths: List[str]
    ) -> Tuple[List[Optional[dict]], Dict[int, int]]: ...
    def exists_many(self, paths: List[str]) -> List[bool]: ...
    def read_many(
        self,
        paths: List[str],
        starts: List[int],
        ends: Optional[List[Optional[int]]] = None,
    ) -> Tuple[List[Optional[bytes]], Dict[int, int]]: ...
    def read_all_many(
        self, paths: List[str]
    ) -> Tuple[List[Optional[bytes]], Dict[int, int]]: ...
    def write_many(
        self, paths: List[str], datas: List[bytes], truncate: bool = True
    ) -> List[int]: ...
    def truncate_many(self, paths: List[str], sizes: List[int]) -> None: ...
    def mkdir_many(self, paths: List[str], mode: int) -> None: ...
    def open_many(self, paths: List[str], modes: List[str]) -> List[int]: ...
    def close_many(self, fds: List[int]) -> None: ...
    def listdir(self, path: str) -> List[dict]: ...
    def listdir_many(
        self, paths: List[str], recursive: bool = False
    ) -> List[List[dict]]: ...
    def walk(self, root: str, sort: bool = True) -> List[Tuple[str, List[dict]]]: ...
    def remove_many(self, paths: List[str]) -> None: ...
    def rename_many(self, pairs: List[Tuple[str, str]]) -> None: ...
    def copy_many(
        self, pairs: List[Tuple[str, str]]
    ) -> Tuple[List[Optional[int]], Dict[int, int]]: ...
    def cp_recursive(self, src: str, dst: str, symlinks: bool = False) -> None: ...
    def rm(self, paths: List[str], recursive: bool) -> None: ...
    def compound_stats(self) -> Tuple[int, int, int, int]: ...
    def rpc_stats(self) -> Tuple[int, int]: ...

def compound_stats_py() -> Tuple[int, int, int, int]: ...
def rpc_stats_py() -> Tuple[int, int]: ...
